sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_d958c2cd1c1f_key -iv $encrypted_d958c2cd1c1f_iv -in gcp-service-account.json.enc -out gcp-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gcp-service-account.json
  - gcloud config set project gcp-k8s-253205
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials gcp-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

script:
  - docker build -t bharanidharan/app:latest -t bharanidharan/app:$SHA .
  - docker push bharanidharan/app:latest
  - docker push bharanidharan/app:$SHA
  - kubectl apply -f k8s
  - kubectl set image deployments/server-deployment server=bharanidharan/app:$SHA

